# Generated by Django 4.2.5 on 2023-10-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_owner_remove_episode_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
